version: "3.8"

services:
  course_hub:
    # platform: amd64
    # network_mode: bridge
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /organization_service/
    restart: always
    command:
      [
        "dumb-init",
        "-cv",
        "--",
        "bash",
        "-c",
        "yarn run start:local"
      ]
    container_name: organization_service
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - .env
    environment:
      - NODE_ENV=local
    networks:
      - My_net
    ports:
      - "3030:3030"
    volumes:
      - ./:/organization_service/
      - node_modules:/organization_service/node_modules
  #############################################################################################################################################################################

volumes:
  node_modules: {}
networks:
  My_net:
    driver: bridge
